-- CONSULTA * TODOS OS DADOS 
SELECT * FROM AUTORES, LIVROS;
SELECT * FROM LIVROS; 

-- CONSULTA POR CAMPOES 
SELECT TITULO FROM LIVROS;
SELECT TITULO, ANO_PUBLICAÇAO FROM LIVROS;

-- CONSULTA POR DATA COM CONDIÇAO 
SELECT TITULO, AUTOR FROM LIVROS
WHERE ANO_PUBLICAÇAO > 2015;

-- CONSULTA POR CRECENTE E DECRECENTE
SELECT TITULO, ANO_PUBLICAÇAO FROM LIVROS
order by ANO_PUBLICAÇAO DESC;

-- CONSULTA POR LIMITE DE RESULTADO 
SELECT TITULO FROM LIVROS
LIMIT 5;

-- RENOMEAR COLUNAS COM AS 
SELECT TITULO AS NOME, AUTOR AS ESCRITOR
FROM LIVROS;

-- FUNÇOES  AGREGADAS 
SELECT count(*) AS TOTAL_LIVROS
FROM LIVROS;

SELECT SUM(PRECO) AS  TOTAL_LIVROS
FROM LIVROS;

SELECT AVG(PRECO) AS TOTAL_LIVROS
FROM LIVROS;

-- AGRUPAMENTOS COM GROUP BY 
SELECT AUTOR, count(*) AS QUANTIDADE
FROM LIVROS
group by AUTOR;

-- USO DE AND OU OR 
SELECT TITULO, PRECO FROM LIVROS
WHERE TITULO = "HARRY" AND PRECO > 30;

SELECT TITULO, PRECO  FROM LIVROS 
WHERE TITULO = "HARRY" OR PRECO > 30;

-- CONDIÇAO EXTRAS COM GROUP BY, HAVING E ORDER BY

SELECT  ID_LIVROS, count(*) AS TOTAL_LIVROS 
FROM LIVROS
GROUP BY ID_AUTOR 
HAVING TOTAL_LIVROS > 5
ORDER BY TOTAL_LIVROS DESC;

-- USO DO LIKE 
SELECT TITULO FROM LIVROS
WHERE TITULO LIKE "%HARRY%";

-- USO DO LIKE COM INICIO POR LETRAS
SELECT TITULO FROM LIVROS 
WHERE TITULO LIKE "%H%";

-- USO DO LIKE COM TERMINO POR LETRAS
SELECT TITULO FROM LIVROS 
WHERE TITULO LIKE "%RY";

-- USO DO LIKE COM QUANTIDADE POR LETRAS
SELECT TITULO FROM LIVROS 
WHERE TITULO LIKE "H___Y";

-- COMBINANDO SITUAÇOES
SELECT TITULO, PRECO FROM LIVROS 
WHERE TITULO LIKE "%HARRY%"
ORDER BY PRECO DESC;
